# Generated by Django 2.1.5 on 2019-02-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=70)),
                ('meta_desc', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True)),
                ('url', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'page',
                'managed': True,
            },
        ),
    ]
