# Generated by Django 2.1.5 on 2019-02-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20190225_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
